interface NestedObject {
    featureName: string;
    isEnabled: boolean;
    version: number;
    createdBy: string;
    createdOn: Date;
    lastUpdatedBy: string;
    lastUpdatedOn: Date;
    compatibility: string;
    supportedLanguages: string[];
    isDeprecated: boolean;
    cId: number;
    pId: number;
}

interface MainObject {
    id: number;
    productName: string;
    description: string;
    isActive: boolean;
    price: number;
    quantity: number;
    category: string;
    rating: number;
    manufacturer: string;
    sku: string;
    releaseDate: Date;
    lastUpdated: Date;
    isInStock: boolean;
    discount: number;
    tags: string[];
    warrantyPeriod: string;
    availableColors: string[];
    features: NestedObject[];
    stockLocation: string;
    dimensions: {
        length: number;
        width: number;
        height: number;
        weight: number;
    };
}

export const data: MainObject[] = [
    {
        id: 1,
        productName: "Smartphone X",
        description: "A high-end smartphone with a powerful processor.",
        isActive: true,
        price: 999,
        quantity: 50,
        category: "Electronics",
        rating: 4.5,
        manufacturer: "TechCorp",
        sku: "TC-SMX-001",
        releaseDate: new Date("2023-05-10"),
        lastUpdated: new Date(),
        isInStock: true,
        discount: 10,
        tags: ["smartphone", "electronics", "gadget"],
        warrantyPeriod: "2 years",
        availableColors: ["black", "white", "blue"],
        features: [
            {
                cId: 1,
                pId: 1,
                featureName: "5G Connectivity",
                isEnabled: true,
                version: 1.0,
                createdBy: "TechCorp",
                createdOn: new Date("2023-01-15"),
                lastUpdatedBy: "TechCorp",
                lastUpdatedOn: new Date("2023-05-01"),
                compatibility: "All carriers",
                supportedLanguages: ["English", "Spanish", "French"],
                isDeprecated: false,
            },
            {
                cId: 2,
                pId: 1,
                featureName: "Face Recognition",
                isEnabled: true,
                version: 2.0,
                createdBy: "TechCorp",
                createdOn: new Date("2023-02-01"),
                lastUpdatedBy: "TechCorp",
                lastUpdatedOn: new Date("2023-04-20"),
                compatibility: "Android",
                supportedLanguages: ["English", "German", "Japanese"],
                isDeprecated: false,
            },
            {
                cId: 7,
                pId: 1,
                featureName: "Wireless Charging",
                isEnabled: true,
                version: 1.2,
                createdBy: "TechCorp",
                createdOn: new Date("2023-03-10"),
                lastUpdatedBy: "TechCorp",
                lastUpdatedOn: new Date("2023-05-05"),
                compatibility: "Qi Standard",
                supportedLanguages: ["English", "Chinese", "Spanish"],
                isDeprecated: false,
            },
            {
                cId: 8,
                pId: 1,
                featureName: "Dual SIM",
                isEnabled: true,
                version: 1.1,
                createdBy: "TechCorp",
                createdOn: new Date("2023-02-25"),
                lastUpdatedBy: "TechCorp",
                lastUpdatedOn: new Date("2023-04-30"),
                compatibility: "All carriers",
                supportedLanguages: ["English", "French", "German"],
                isDeprecated: false,
            },
            {
                cId: 9,
                pId: 1,
                featureName: "High Refresh Rate Display",
                isEnabled: true,
                version: 1.3,
                createdBy: "TechCorp",
                createdOn: new Date("2023-03-20"),
                lastUpdatedBy: "TechCorp",
                lastUpdatedOn: new Date("2023-05-10"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Spanish", "French"],
                isDeprecated: false,
            },
            {
                cId: 10,
                pId: 1,
                featureName: "In-display Fingerprint Sensor",
                isEnabled: true,
                version: 2.2,
                createdBy: "TechCorp",
                createdOn: new Date("2023-04-05"),
                lastUpdatedBy: "TechCorp",
                lastUpdatedOn: new Date("2023-05-15"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Chinese", "Japanese"],
                isDeprecated: false,
            },
            {
                cId: 11,
                pId: 1,
                featureName: "AI Camera",
                isEnabled: true,
                version: 3.1,
                createdBy: "TechCorp",
                createdOn: new Date("2023-04-15"),
                lastUpdatedBy: "TechCorp",
                lastUpdatedOn: new Date("2023-05-20"),
                compatibility: "All devices",
                supportedLanguages: ["English", "German", "Italian"],
                isDeprecated: false,
            },
            {
                cId: 12,
                pId: 1,
                featureName: "Fast Charging",
                isEnabled: true,
                version: 2.0,
                createdBy: "TechCorp",
                createdOn: new Date("2023-04-25"),
                lastUpdatedBy: "TechCorp",
                lastUpdatedOn: new Date("2023-05-25"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Spanish", "French"],
                isDeprecated: false,
            },
            {
                cId: 13,
                pId: 1,
                featureName: "Expandable Storage",
                isEnabled: true,
                version: 1.1,
                createdBy: "TechCorp",
                createdOn: new Date("2023-05-01"),
                lastUpdatedBy: "TechCorp",
                lastUpdatedOn: new Date("2023-05-30"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Chinese", "Japanese"],
                isDeprecated: false,
            },
            {
                cId: 14,
                pId: 1,
                featureName: "Waterproof",
                isEnabled: true,
                version: 1.0,
                createdBy: "TechCorp",
                createdOn: new Date("2023-05-10"),
                lastUpdatedBy: "TechCorp",
                lastUpdatedOn: new Date("2023-06-01"),
                compatibility: "All devices",
                supportedLanguages: ["English", "German", "Italian"],
                isDeprecated: false,
            },
            {
                cId: 15,
                pId: 1,
                featureName: "Wireless Data Transfer",
                isEnabled: true,
                version: 2.1,
                createdBy: "TechCorp",
                createdOn: new Date("2023-05-20"),
                lastUpdatedBy: "TechCorp",
                lastUpdatedOn: new Date("2023-06-05"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Spanish", "French"],
                isDeprecated: false,
            },
            {
                cId: 16,
                pId: 1,
                featureName: "Voice Assistant",
                isEnabled: true,
                version: 3.0,
                createdBy: "TechCorp",
                createdOn: new Date("2023-05-25"),
                lastUpdatedBy: "TechCorp",
                lastUpdatedOn: new Date("2023-06-10"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Chinese", "Japanese"],
                isDeprecated: false,
            },
            {
                cId: 17,
                pId: 1,
                featureName: "Augmented Reality",
                isEnabled: true,
                version: 1.5,
                createdBy: "TechCorp",
                createdOn: new Date("2023-06-01"),
                lastUpdatedBy: "TechCorp",
                lastUpdatedOn: new Date("2023-06-15"),
                compatibility: "All devices",
                supportedLanguages: ["English", "German", "Italian"],
                isDeprecated: false,
            },
            {
                cId: 18,
                pId: 1,
                featureName: "Health Monitoring",
                isEnabled: true,
                version: 2.3,
                createdBy: "TechCorp",
                createdOn: new Date("2023-06-05"),
                lastUpdatedBy: "TechCorp",
                lastUpdatedOn: new Date("2023-06-20"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Spanish", "French"],
                isDeprecated: false,
            },
        ],
        stockLocation: "Warehouse A",
        dimensions: {
            length: 15,
            width: 7,
            height: 0.8,
            weight: 180,
        },
    },
    {
        id: 2,
        productName: "Laptop Pro",
        description: "A powerful laptop for professionals.",
        isActive: true,
        price: 1999,
        quantity: 30,
        category: "Computers",
        rating: 4.8,
        manufacturer: "CompTech",
        sku: "CT-LP-002",
        releaseDate: new Date("2023-03-15"),
        lastUpdated: new Date(),
        isInStock: true,
        discount: 15,
        tags: ["laptop", "computers", "professional"],
        warrantyPeriod: "3 years",
        availableColors: ["silver", "gray"],
        features: [
            {
                cId: 3,
                pId: 2,
                featureName: "Touchscreen",
                isEnabled: true,
                version: 3.0,
                createdBy: "CompTech",
                createdOn: new Date("2023-01-10"),
                lastUpdatedBy: "CompTech",
                lastUpdatedOn: new Date("2023-03-01"),
                compatibility: "Windows",
                supportedLanguages: ["English", "Chinese", "Korean"],
                isDeprecated: false,
            },
            {
                cId: 4,
                pId: 2,
                featureName: "Backlit Keyboard",
                isEnabled: true,
                version: 1.5,
                createdBy: "CompTech",
                createdOn: new Date("2023-02-20"),
                lastUpdatedBy: "CompTech",
                lastUpdatedOn: new Date("2023-04-10"),
                compatibility: "All OS",
                supportedLanguages: ["English", "Spanish", "Italian"],
                isDeprecated: false,
            },
            {
                cId: 19,
                pId: 2,
                featureName: "Fingerprint Sensor",
                isEnabled: true,
                version: 2.0,
                createdBy: "CompTech",
                createdOn: new Date("2023-03-01"),
                lastUpdatedBy: "CompTech",
                lastUpdatedOn: new Date("2023-05-01"),
                compatibility: "All OS",
                supportedLanguages: ["English", "Spanish", "French"],
                isDeprecated: false,
            },
            {
                cId: 20,
                pId: 2,
                featureName: "Thunderbolt 3",
                isEnabled: true,
                version: 1.0,
                createdBy: "CompTech",
                createdOn: new Date("2023-03-15"),
                lastUpdatedBy: "CompTech",
                lastUpdatedOn: new Date("2023-05-15"),
                compatibility: "All OS",
                supportedLanguages: ["English", "Chinese", "Japanese"],
                isDeprecated: false,
            },
            {
                cId: 21,
                pId: 2,
                featureName: "Wi-Fi 6",
                isEnabled: true,
                version: 1.2,
                createdBy: "CompTech",
                createdOn: new Date("2023-04-01"),
                lastUpdatedBy: "CompTech",
                lastUpdatedOn: new Date("2023-06-01"),
                compatibility: "All OS",
                supportedLanguages: ["English", "German", "Italian"],
                isDeprecated: false,
            },
            {
                cId: 22,
                pId: 2,
                featureName: "Bluetooth 5.0",
                isEnabled: true,
                version: 1.1,
                createdBy: "CompTech",
                createdOn: new Date("2023-04-10"),
                lastUpdatedBy: "CompTech",
                lastUpdatedOn: new Date("2023-06-10"),
                compatibility: "All OS",
                supportedLanguages: ["English", "Spanish", "French"],
                isDeprecated: false,
            },
            {
                cId: 23,
                pId: 2,
                featureName: "HD Webcam",
                isEnabled: true,
                version: 2.0,
                createdBy: "CompTech",
                createdOn: new Date("2023-04-20"),
                lastUpdatedBy: "CompTech",
                lastUpdatedOn: new Date("2023-06-20"),
                compatibility: "All OS",
                supportedLanguages: ["English", "Chinese", "Japanese"],
                isDeprecated: false,
            },
            {
                cId: 24,
                pId: 2,
                featureName: "SSD Storage",
                isEnabled: true,
                version: 1.3,
                createdBy: "CompTech",
                createdOn: new Date("2023-05-01"),
                lastUpdatedBy: "CompTech",
                lastUpdatedOn: new Date("2023-07-01"),
                compatibility: "All OS",
                supportedLanguages: ["English", "German", "Italian"],
                isDeprecated: false,
            },
            {
                cId: 25,
                pId: 2,
                featureName: "4K Display",
                isEnabled: true,
                version: 2.1,
                createdBy: "CompTech",
                createdOn: new Date("2023-05-10"),
                lastUpdatedBy: "CompTech",
                lastUpdatedOn: new Date("2023-07-10"),
                compatibility: "All OS",
                supportedLanguages: ["English", "Spanish", "French"],
                isDeprecated: false,
            },
            {
                cId: 26,
                pId: 2,
                featureName: "Long Battery Life",
                isEnabled: true,
                version: 1.0,
                createdBy: "CompTech",
                createdOn: new Date("2023-05-20"),
                lastUpdatedBy: "CompTech",
                lastUpdatedOn: new Date("2023-07-20"),
                compatibility: "All OS",
                supportedLanguages: ["English", "Chinese", "Japanese"],
                isDeprecated: false,
            },
            {
                cId: 27,
                pId: 2,
                featureName: "Fast Boot",
                isEnabled: true,
                version: 1.2,
                createdBy: "CompTech",
                createdOn: new Date("2023-06-01"),
                lastUpdatedBy: "CompTech",
                lastUpdatedOn: new Date("2023-08-01"),
                compatibility: "All OS",
                supportedLanguages: ["English", "German", "Italian"],
                isDeprecated: false,
            },
            {
                cId: 28,
                pId: 2,
                featureName: "Virtual Reality Ready",
                isEnabled: true,
                version: 2.0,
                createdBy: "CompTech",
                createdOn: new Date("2023-06-10"),
                lastUpdatedBy: "CompTech",
                lastUpdatedOn: new Date("2023-08-10"),
                compatibility: "All OS",
                supportedLanguages: ["English", "Spanish", "French"],
                isDeprecated: false,
            },
        ],
        stockLocation: "Warehouse B",
        dimensions: {
            length: 35,
            width: 24,
            height: 1.8,
            weight: 1500,
        },
    },
    {
        id: 3,
        productName: "Wireless Earbuds",
        description: "Compact and high-quality wireless earbuds.",
        isActive: true,
        price: 199,
        quantity: 100,
        category: "Audio",
        rating: 4.3,
        manufacturer: "SoundWave",
        sku: "SW-WE-003",
        releaseDate: new Date("2023-06-01"),
        lastUpdated: new Date(),
        isInStock: true,
        discount: 5,
        tags: ["earbuds", "audio", "wireless"],
        warrantyPeriod: "1 year",
        availableColors: ["black", "white"],
        features: [
            {
                cId: 5,
                pId: 3,
                featureName: "Noise Cancellation",
                isEnabled: true,
                version: 2.1,
                createdBy: "SoundWave",
                createdOn: new Date("2023-03-05"),
                lastUpdatedBy: "SoundWave",
                lastUpdatedOn: new Date("2023-05-15"),
                compatibility: "All devices",
                supportedLanguages: ["English", "French", "Spanish"],
                isDeprecated: false,
            },
            {
                cId: 6,
                pId: 3,
                featureName: "Water Resistant",
                isEnabled: true,
                version: 1.0,
                createdBy: "SoundWave",
                createdOn: new Date("2023-04-01"),
                lastUpdatedBy: "SoundWave",
                lastUpdatedOn: new Date("2023-06-01"),
                compatibility: "All devices",
                supportedLanguages: ["English", "German", "Japanese"],
                isDeprecated: false,
            },
            {
                cId: 29,
                pId: 3,
                featureName: "Wireless Charging Case",
                isEnabled: true,
                version: 1.0,
                createdBy: "SoundWave",
                createdOn: new Date("2023-04-15"),
                lastUpdatedBy: "SoundWave",
                lastUpdatedOn: new Date("2023-06-15"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Chinese", "Spanish"],
                isDeprecated: false,
            },
            {
                cId: 30,
                pId: 3,
                featureName: "Touch Controls",
                isEnabled: true,
                version: 1.2,
                createdBy: "SoundWave",
                createdOn: new Date("2023-05-01"),
                lastUpdatedBy: "SoundWave",
                lastUpdatedOn: new Date("2023-07-01"),
                compatibility: "All devices",
                supportedLanguages: ["English", "German", "Italian"],
                isDeprecated: false,
            },
            {
                cId: 31,
                pId: 3,
                featureName: "Voice Assistant Integration",
                isEnabled: true,
                version: 2.0,
                createdBy: "SoundWave",
                createdOn: new Date("2023-05-10"),
                lastUpdatedBy: "SoundWave",
                lastUpdatedOn: new Date("2023-07-10"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Spanish", "French"],
                isDeprecated: false,
            },
            {
                cId: 32,
                pId: 3,
                featureName: "Long Battery Life",
                isEnabled: true,
                version: 1.1,
                createdBy: "SoundWave",
                createdOn: new Date("2023-05-20"),
                lastUpdatedBy: "SoundWave",
                lastUpdatedOn: new Date("2023-07-20"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Chinese", "Japanese"],
                isDeprecated: false,
            },
            {
                cId: 33,
                pId: 3,
                featureName: "Customizable Sound Profiles",
                isEnabled: true,
                version: 1.3,
                createdBy: "SoundWave",
                createdOn: new Date("2023-06-01"),
                lastUpdatedBy: "SoundWave",
                lastUpdatedOn: new Date("2023-08-01"),
                compatibility: "All devices",
                supportedLanguages: ["English", "German", "Italian"],
                isDeprecated: false,
            },
        ],
        stockLocation: "Warehouse C",
        dimensions: {
            length: 5,
            width: 2,
            height: 2,
            weight: 50,
        },
    },
    {
        id: 4,
        productName: "Smartwatch Z",
        description: "A sleek smartwatch with multiple health tracking features.",
        isActive: true,
        price: 299,
        quantity: 75,
        category: "Wearables",
        rating: 4.6,
        manufacturer: "WearTech",
        sku: "WT-SWZ-004",
        releaseDate: new Date("2023-04-20"),
        lastUpdated: new Date(),
        isInStock: true,
        discount: 8,
        tags: ["smartwatch", "wearables", "health"],
        warrantyPeriod: "2 years",
        availableColors: ["black", "silver", "rose gold"],
        features: [
            {
                cId: 34,
                pId: 4,
                featureName: "Heart Rate Monitor",
                isEnabled: true,
                version: 1.0,
                createdBy: "WearTech",
                createdOn: new Date("2023-01-10"),
                lastUpdatedBy: "WearTech",
                lastUpdatedOn: new Date("2023-03-01"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Spanish", "French"],
                isDeprecated: false,
            },
            {
                cId: 35,
                pId: 4,
                featureName: "Sleep Tracking",
                isEnabled: true,
                version: 1.2,
                createdBy: "WearTech",
                createdOn: new Date("2023-02-15"),
                lastUpdatedBy: "WearTech",
                lastUpdatedOn: new Date("2023-04-01"),
                compatibility: "All devices",
                supportedLanguages: ["English", "German", "Japanese"],
                isDeprecated: false,
            },
            {
                cId: 36,
                pId: 4,
                featureName: "GPS Navigation",
                isEnabled: true,
                version: 2.0,
                createdBy: "WearTech",
                createdOn: new Date("2023-03-05"),
                lastUpdatedBy: "WearTech",
                lastUpdatedOn: new Date("2023-05-01"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Chinese", "Spanish"],
                isDeprecated: false,
            },
            {
                cId: 37,
                pId: 4,
                featureName: "Water Resistant",
                isEnabled: true,
                version: 1.1,
                createdBy: "WearTech",
                createdOn: new Date("2023-03-20"),
                lastUpdatedBy: "WearTech",
                lastUpdatedOn: new Date("2023-05-15"),
                compatibility: "All devices",
                supportedLanguages: ["English", "German", "Italian"],
                isDeprecated: false,
            },
            {
                cId: 38,
                pId: 4,
                featureName: "Voice Assistant",
                isEnabled: true,
                version: 2.1,
                createdBy: "WearTech",
                createdOn: new Date("2023-04-01"),
                lastUpdatedBy: "WearTech",
                lastUpdatedOn: new Date("2023-06-01"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Spanish", "French"],
                isDeprecated: false,
            },
            {
                cId: 39,
                pId: 4,
                featureName: "Customizable Watch Faces",
                isEnabled: true,
                version: 1.3,
                createdBy: "WearTech",
                createdOn: new Date("2023-04-15"),
                lastUpdatedBy: "WearTech",
                lastUpdatedOn: new Date("2023-06-15"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Chinese", "Japanese"],
                isDeprecated: false,
            },
        ],
        stockLocation: "Warehouse D",
        dimensions: {
            length: 4,
            width: 4,
            height: 1,
            weight: 50,
        },
    },
    {
        id: 5,
        productName: "Gaming Console Y",
        description: "A next-gen gaming console with stunning graphics.",
        isActive: true,
        price: 499,
        quantity: 40,
        category: "Gaming",
        rating: 4.9,
        manufacturer: "GameTech",
        sku: "GT-GCY-005",
        releaseDate: new Date("2023-02-25"),
        lastUpdated: new Date(),
        isInStock: true,
        discount: 12,
        tags: ["gaming", "console", "entertainment"],
        warrantyPeriod: "3 years",
        availableColors: ["black", "white"],
        features: [
            {
                cId: 40,
                pId: 5,
                featureName: "4K Gaming",
                isEnabled: true,
                version: 1.0,
                createdBy: "GameTech",
                createdOn: new Date("2023-01-05"),
                lastUpdatedBy: "GameTech",
                lastUpdatedOn: new Date("2023-03-01"),
                compatibility: "All games",
                supportedLanguages: ["English", "Spanish", "French"],
                isDeprecated: false,
            },
            {
                cId: 41,
                pId: 5,
                featureName: "Virtual Reality Support",
                isEnabled: true,
                version: 2.0,
                createdBy: "GameTech",
                createdOn: new Date("2023-02-10"),
                lastUpdatedBy: "GameTech",
                lastUpdatedOn: new Date("2023-04-01"),
                compatibility: "All VR headsets",
                supportedLanguages: ["English", "German", "Japanese"],
                isDeprecated: false,
            },
            {
                cId: 42,
                pId: 5,
                featureName: "Online Multiplayer",
                isEnabled: true,
                version: 3.0,
                createdBy: "GameTech",
                createdOn: new Date("2023-02-20"),
                lastUpdatedBy: "GameTech",
                lastUpdatedOn: new Date("2023-05-01"),
                compatibility: "All networks",
                supportedLanguages: ["English", "Chinese", "Spanish"],
                isDeprecated: false,
            },
            {
                cId: 43,
                pId: 5,
                featureName: "Backward Compatibility",
                isEnabled: true,
                version: 1.1,
                createdBy: "GameTech",
                createdOn: new Date("2023-03-01"),
                lastUpdatedBy: "GameTech",
                lastUpdatedOn: new Date("2023-05-15"),
                compatibility: "Previous gen games",
                supportedLanguages: ["English", "German", "Italian"],
                isDeprecated: false,
            },
            {
                cId: 44,
                pId: 5,
                featureName: "Voice Control",
                isEnabled: true,
                version: 2.1,
                createdBy: "GameTech",
                createdOn: new Date("2023-03-15"),
                lastUpdatedBy: "GameTech",
                lastUpdatedOn: new Date("2023-06-01"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Spanish", "French"],
                isDeprecated: false,
            },
            {
                cId: 45,
                pId: 5,
                featureName: "Customizable Controllers",
                isEnabled: true,
                version: 1.3,
                createdBy: "GameTech",
                createdOn: new Date("2023-04-01"),
                lastUpdatedBy: "GameTech",
                lastUpdatedOn: new Date("2023-06-15"),
                compatibility: "All devices",
                supportedLanguages: ["English", "Chinese", "Japanese"],
                isDeprecated: false,
            },
        ],
        stockLocation: "Warehouse E",
        dimensions: {
            length: 30,
            width: 20,
            height: 10,
            weight: 3000,
        },
    }
    // Add more main objects here
];
